### ISSUE TITLE
Launchpad Pro?

### ISSUE THREAD

**Issue by TheProgrammer11** [dszakallas/mixxx-launchpad#13]
?????

**Comment by szdavid92** [comment]
I need a helping hand for this, because I don't have a Launchpad Pro. :)
There are two main concerns that I am aware of:
1. mapping the existing layouts to Pro.
2. leveraging the additional pads Pro has.


The first point seems easy to implement, basically creating a [new target](https://github.com/szdavid92/mixxx-launchpad/blob/master/package.json#L39), and creating the additional packag with the new target analogously to [mk2](https://github.com/szdavid92/mixxx-launchpad/tree/master/packages/mk2) and the adapted button and color specification [mk-specs@2.0.0](https://github.com/szdavid92/mixxx-launchpad/tree/master/packages/mk-specs%402.0.0) and testing that it indeed works.

The second point is harder and involves some design steps.

**Comment by TheProgrammer11** [comment]
Yea i have a launchpad pro and can help. :)

**Comment by szdavid92** [comment]
If you feel comfortable with submitting a PR for the first task, here's the [Programmer's Guide for Pro](https://global.novationmusic.com/sites/default/files/novation/downloads/10598/launchpad-pro-programmers-reference-guide_0.pdf), where you can find the button and the colour mappings.

**Comment by TheProgrammer11** [comment]
Yea i can try 

might take me a while though.
 
:)

**Comment by szdavid92** [comment]
Just ping me if you are stuck with something. I am currently working on making the build a bit friendlier.

**Comment by TheProgrammer11** [comment]
Yea ok

Should i make a pull request or just download a zip of it

**Comment by TheProgrammer11** [comment]
?

**Comment by szdavid92** [comment]
The basic process is forking the repo, working on the code and submitting a PR. The zip is distribution, with bundled and transpiled code, you don't really want to work on that :)

If you are unfamiliar with the process [here's a quick guide](https://guides.github.com/activities/forking/)

**Comment by TheProgrammer11** [comment]
Ok thanks

**Comment by TheProgrammer11** [comment]
I can't clone into the repo

it says that i do not have the perms

**Comment by TheProgrammer11** [comment]
this was trying to clone into the fork

**Comment by TheProgrammer11** [comment]
?

**Comment by dszakallas** [comment]
I added support for Pro in PR #16 . Please check out the branch, and try it locally.

**Comment by TheProgrammer11** [comment]
I tried to build the source locally but make said that it couldn't built default

**Comment by TheProgrammer11** [comment]
![untitled 6](https://user-images.githubusercontent.com/9887505/39707044-231228f6-520b-11e8-9f87-63fd4a1970f5.png)

**Comment by TheProgrammer11** [comment]
This is the built error I get

**Comment by dszakallas** [comment]
you need to have a newer bash. Default bash on MacOS is way too old. See building instructions.

**Comment by TheProgrammer11** [comment]
ok will try again later when I get home

**Comment by dszakallas** [comment]
I added experimental support in https://github.com/dszakallas/mixxx-launchpad/releases/tag/v2.2.0
Check out and open an issue if you face any problems. Thanks.
